version: 0.1
phases:
  install:
    commands:
      - npm install -g serverless
      - serverless config credentials --provider aws --key $key --secret $secret
  build:
    commands:
      - npm install
  post_build:
    commands:
      - serverless deploy --stage $env
