version: 0.1
phases:
  install:
    commands:
      - npm install
      – npm install -g serverless
build:
commands:
post_build:
commands:
– serverless deploy –stage prod –region ap-southeast-1 –verbose
